/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 04/Jan/2021 21:47:40
** YOU CAN MODIFY IT, as it will not be regenerated.
** If you want to regenrate this file simply delete it.
*/
using System;
using System.Collections.Generic;
using System.Linq;
using uPromis.Microservice.ContractAPI.Models;

namespace uPromis.Microservice.ContractAPI.Business
{
    partial class ContractBusinessRules : IContractBusinessRules
    {
        partial void OnApplyBusinessRules(uPromis.Microservice.ContractAPI.Models.Contract Record, ContractDTO DTORecord, IRepository<uPromis.Microservice.ContractAPI.Models.Contract> Repository)
        {
            double paymentTotals = DTORecord.Payments.Sum( p => p.Modifier != "Deleted" ? p.Amount : 0.0 );
            if (paymentTotals != DTORecord.Budget)
            {
                results.Add(new BusinessRuleResult() { 
                    Property = "Budget", 
                    Message = string.Format("Total of payment lines {0:#,##0.00} is not equal to the contract budget {1:#,##0.00}.", paymentTotals, DTORecord.Budget), 
                    Severity = BusinessRuleResultSeverity.Warning });
            }
        }
    }
}
