/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 04/Jan/2021 21:46:21
** YOU CAN MODIFY IT, as it will not be regenerated.
** If you want to regenrate this file simply delete it.
*/
using System;
using System.Collections.Generic;
using uPromis.Microservice.ContractAPI.Models;

namespace uPromis.Microservice.ContractAPI.Business
{
    partial class RequestBusinessRules : IRequestBusinessRules
    {
        partial void OnApplyBusinessRules(Request Record, RequestDTO DTORecord, IRepository<Request> Repository)
        {

        }
    }
}
