/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 18/Dec/2020 22:34:53
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
using APIUtils.APIMessaging;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace upromiscontractapi.Models
{

    public class AccountInfoRepository : IAccountInfoRepository
    {
        ContractDbContext Context { get; set; }

        public AccountInfoRepository(ContractDbContext context)
        {
            Context = context;

        }
        public IQueryable<AccountInfo> List => Context.Accounts
        ;

        public async Task<AccountInfoDTO> Post(SaveMessage<AccountInfoDTO> rec)
        {
            // TODO: add validations
            // TODO: check for new users to create in the team composition list

            AccountInfo record = Transformers.Transform(rec.DataSubject, new AccountInfo()) as AccountInfo;

            record.AccountFields.ForEach(pi =>
            {
                pi.AccountInfo = record;
            });
            record.Teammembers.ForEach(pi =>
            {
                pi.AccountInfo = record;
            });

//            record.AccountInfo = Context.AccountInfo.FirstOrDefault();

//            record.ParentContract = Context.Contracts.Find(rec.DataSubject.ParentContractID);

            Context.Accounts.Add(record);

            await Context.SaveChangesAsync();

            return Transformers.Transform(record, new AccountInfoDTO());
        }

        public async Task<AccountInfoDTO> Put(SaveMessage<AccountInfoDTO> rec)
        {
            var ctr = await Context.Accounts.Where(c => c.ID == rec.ID)
                .Include( p => p.AccountFields)
                .Include( p => p.Teammembers)
                .Include( p => p.Contracts)
                .Include( p => p.Proposals)
                .Include( p => p.Requests)
                .FirstOrDefaultAsync();

            if (ctr == null)
            {
                return null;
            }

            ctr = Transformers.Transform(rec.DataSubject, ctr);

            await Context.SaveChangesAsync();

            return Transformers.Transform(ctr, new AccountInfoDTO());
        }

        public async Task<bool> Delete(SaveMessage<AccountInfoDTO> rec)
        {
            var ctr = Context.Accounts.FirstOrDefault(c => c.ID == rec.ID);

            if (ctr == null)
            {
                return false;
            }

            Context.Accounts.Remove(ctr);

            await Context.SaveChangesAsync();

            return true;
        }

        public async Task<AccountInfoDTO> Get(int id)
        {
            var record = await Context.Accounts.Where(c => c.ID == id)
                .Include( p => p.AccountFields)
                .Include( p => p.Teammembers)
                .Include( p => p.Contracts)
                .Include( p => p.Proposals)
                .Include( p => p.Requests)
                .FirstOrDefaultAsync();

            var ctr = Transformers.Transform(record, new AccountInfoDTO() { Modifier = "Unchanged" });

            return ctr;
        }


        public async Task<List<ListValue>> GetProposalIdReference()
        {
        var ct = Context;
        var records = ct.Proposals;
        return await records.Select( s => new ListValue() { Value = s.ID, Label = s.Title}).ToListAsync();
}

    }
}
