/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 01/Oct/2020 22:57:30
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
namespace upromiscontractapi.Models
{
    public interface IAccountInfoRepository : IRepository<AccountInfoDTO>
    {
    }
}
