/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 18/Dec/2020 22:34:53
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
using APIUtils.APIMessaging;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace upromiscontractapi.Models
{
    public interface IAccountInfoRepository : IRepository<AccountInfoDTO, AccountInfo>
    {

        public Task<List<ListValue>> GetProposalIdReference();
    }
}
