/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 28/Dec/2020 21:46:20
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
using APIUtils.APIMessaging;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace upromiscontractapi.Models
{
    public interface IRequestRepository : IRepository<Request>
    {

    }
}
