/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 01/Oct/2020 22:57:34
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
using APIUtils.APIMessaging;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace upromiscontractapi.Models
{

    public class ProposalRepository : IProposalRepository
    {
        ContractDbContext _context { get; set; }

        public ProposalRepository(ContractDbContext context)
        {
            _context = context;

        }
        public IQueryable<ProposalDTO> List => _context.Proposals.Select(c => Transformers.Transform(c, new ProposalDTO() { Modifier = "Unchanged" })).AsQueryable();

        public async Task<ProposalDTO> Post(SaveMessage<ProposalDTO> rec)
        {
            // TODO: add validations
            // TODO: check for new users to create in the team composition list

            Proposal record = Transformers.Transform(rec.DataSubject, new Proposal()) as Proposal;

            record.Payments.ForEach(pi =>
            {
                pi.Proposal = record;
            });
            record.Teammembers.ForEach(pi =>
            {
                pi.Proposal = record;
            });

//            record.AccountInfo = _context.AccountInfo.FirstOrDefault();

//            record.ParentContract = _context.Contracts.Find(rec.DataSubject.ParentContractID);

            _context.Proposals.Add(record);

            await _context.SaveChangesAsync();

            return Transformers.Transform(record, new ProposalDTO());
        }

        public async Task<ProposalDTO> Put(SaveMessage<ProposalDTO> rec)
        {
            var ctr = await _context.Proposals.Where(c => c.ID == rec.ID)
                .Include("ProposalPaymentInfo")
                .Include("ProposalTeamComposition")
                .FirstOrDefaultAsync();

            if (ctr == null)
            {
                return null;
            }

            ctr = Transformers.Transform(rec.DataSubject, ctr);

            await _context.SaveChangesAsync();

            return Transformers.Transform(ctr, new ProposalDTO());
        }

        public async Task<bool> Delete(SaveMessage<ProposalDTO> rec)
        {
            var ctr = _context.Proposals.FirstOrDefault(c => c.ID == rec.ID);

            if (ctr == null)
            {
                return false;
            }

            _context.Proposals.Remove(ctr);

            await _context.SaveChangesAsync();

            return true;
        }

        public async Task<ProposalDTO> Get(int id)
        {
            var record = await _context.Proposals.Where(c => c.ID == id)
                .Include("ProposalPaymentInfo")
                .Include("ProposalTeamComposition")
                .FirstOrDefaultAsync();

            var ctr = Transformers.Transform(record, new ProposalDTO() { Modifier = "Unchanged" });

            return ctr;
        }
    }
}
