/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 18/Dec/2020 22:34:55
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
using APIUtils.APIMessaging;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace upromiscontractapi.Models
{

    public class ProposalRepository : IProposalRepository
    {
        ContractDbContext Context { get; set; }

        public ProposalRepository(ContractDbContext context)
        {
            Context = context;

        }
        public IQueryable<Proposal> List => Context.Proposals
        ;

        public async Task<ProposalDTO> Post(SaveMessage<ProposalDTO> rec)
        {
            // TODO: add validations
            // TODO: check for new users to create in the team composition list

            Proposal record = Transformers.Transform(rec.DataSubject, new Proposal()) as Proposal;

            record.Payments.ForEach(pi =>
            {
                pi.Proposal = record;
            });
            record.Teammembers.ForEach(pi =>
            {
                pi.Proposal = record;
            });

//            record.AccountInfo = Context.AccountInfo.FirstOrDefault();

//            record.ParentContract = Context.Contracts.Find(rec.DataSubject.ParentContractID);

            Context.Proposals.Add(record);

            await Context.SaveChangesAsync();

            return Transformers.Transform(record, new ProposalDTO());
        }

        public async Task<ProposalDTO> Put(SaveMessage<ProposalDTO> rec)
        {
            var ctr = await Context.Proposals.Where(c => c.ID == rec.ID)
                .Include( p => p.Payments)
                .Include( p => p.Teammembers)
                .FirstOrDefaultAsync();

            if (ctr == null)
            {
                return null;
            }

            ctr = Transformers.Transform(rec.DataSubject, ctr);

            await Context.SaveChangesAsync();

            return Transformers.Transform(ctr, new ProposalDTO());
        }

        public async Task<bool> Delete(SaveMessage<ProposalDTO> rec)
        {
            var ctr = Context.Proposals.FirstOrDefault(c => c.ID == rec.ID);

            if (ctr == null)
            {
                return false;
            }

            Context.Proposals.Remove(ctr);

            await Context.SaveChangesAsync();

            return true;
        }

        public async Task<ProposalDTO> Get(int id)
        {
            var record = await Context.Proposals.Where(c => c.ID == id)
                .Include( p => p.Payments)
                .Include( p => p.Teammembers)
                .FirstOrDefaultAsync();

            var ctr = Transformers.Transform(record, new ProposalDTO() { Modifier = "Unchanged" });

            return ctr;
        }

    }
}
