/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 28/Dec/2020 21:46:20
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace upromiscontractapi.Models
{


    public class ProposalDTO : DTOBase
    {
        [Key]
        [Required]
        [JsonProperty(PropertyName = "id")]
        public int ID { get; set; } 

        [Required]
        [JsonProperty(PropertyName = "externalId")]
        public Guid ExternalID { get; set; } = Guid.NewGuid(); 

        [Required]
        [StringLength(50)]
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; } 

        [Required]
        [StringLength(100)]
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; } 

        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; } 

        [DisplayFormat(DataFormatString = "{0:MM/DD/YYYY}")]
        [JsonProperty(PropertyName = "startDate")]
        public DateTime Startdate { get; set; } = DateTime.Now; 

        [DisplayFormat(DataFormatString = "{0:MM/DD/YYYY}")]
        [JsonProperty(PropertyName = "endDate")]
        public DateTime Enddate { get; set; } = DateTime.Now; 

        [Required]
        [StringLength(50)]
        [JsonProperty(PropertyName = "proposalStatus")]
        public string ProposalStatus { get; set; } 
        [JsonProperty(PropertyName = "proposalStatusLabel")]
        public string ProposalStatusLabel { get; set; }

        [Required]
        [StringLength(50)]
        [JsonProperty(PropertyName = "proposalType")]
        public string ProposalType { get; set; } 
        [JsonProperty(PropertyName = "proposalTypeLabel")]
        public string ProposalTypeLabel { get; set; }


        // Default model properties
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        public DateTime CreatedOn { get; set; } = DateTime.Now;

        public string CreatedBy { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;

        public string UpdatedBy { get; set; }

        [JsonProperty(PropertyName = "Payments")]
        public virtual List<ProposalPaymentInfoDTO> Payments { get; private set; } = new List<ProposalPaymentInfoDTO>();
        [JsonProperty(PropertyName = "Teammembers")]
        public virtual List<ProposalTeamCompositionDTO> Teammembers { get; private set; } = new List<ProposalTeamCompositionDTO>();

    }
}

