/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 01/Oct/2020 22:57:33
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
using APIUtils.APIMessaging;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace upromiscontractapi.Models
{

    public class RequestRepository : IRequestRepository
    {
        ContractDbContext _context { get; set; }

        public RequestRepository(ContractDbContext context)
        {
            _context = context;

        }
        public IQueryable<RequestDTO> List => _context.Requests.Select(c => Transformers.Transform(c, new RequestDTO() { Modifier = "Unchanged" })).AsQueryable();

        public async Task<RequestDTO> Post(SaveMessage<RequestDTO> rec)
        {
            // TODO: add validations
            // TODO: check for new users to create in the team composition list

            Request record = Transformers.Transform(rec.DataSubject, new Request()) as Request;

            record.Teammembers.ForEach(pi =>
            {
                pi.Request = record;
            });

//            record.AccountInfo = _context.AccountInfo.FirstOrDefault();

//            record.ParentContract = _context.Contracts.Find(rec.DataSubject.ParentContractID);

            _context.Requests.Add(record);

            await _context.SaveChangesAsync();

            return Transformers.Transform(record, new RequestDTO());
        }

        public async Task<RequestDTO> Put(SaveMessage<RequestDTO> rec)
        {
            var ctr = await _context.Requests.Where(c => c.ID == rec.ID)
                .Include("RequestTeamComposition")
                .FirstOrDefaultAsync();

            if (ctr == null)
            {
                return null;
            }

            ctr = Transformers.Transform(rec.DataSubject, ctr);

            await _context.SaveChangesAsync();

            return Transformers.Transform(ctr, new RequestDTO());
        }

        public async Task<bool> Delete(SaveMessage<RequestDTO> rec)
        {
            var ctr = _context.Requests.FirstOrDefault(c => c.ID == rec.ID);

            if (ctr == null)
            {
                return false;
            }

            _context.Requests.Remove(ctr);

            await _context.SaveChangesAsync();

            return true;
        }

        public async Task<RequestDTO> Get(int id)
        {
            var record = await _context.Requests.Where(c => c.ID == id)
                .Include("RequestTeamComposition")
                .FirstOrDefaultAsync();

            var ctr = Transformers.Transform(record, new RequestDTO() { Modifier = "Unchanged" });

            return ctr;
        }
    }
}
