/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 18/Dec/2020 22:34:55
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/
using APIUtils.APIMessaging;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace upromiscontractapi.Models
{

    public class RequestRepository : IRequestRepository
    {
        ContractDbContext Context { get; set; }

        public RequestRepository(ContractDbContext context)
        {
            Context = context;

        }
        public IQueryable<Request> List => Context.Requests
        ;

        public async Task<RequestDTO> Post(SaveMessage<RequestDTO> rec)
        {
            // TODO: add validations
            // TODO: check for new users to create in the team composition list

            Request record = Transformers.Transform(rec.DataSubject, new Request()) as Request;

            record.Teammembers.ForEach(pi =>
            {
                pi.Request = record;
            });

//            record.AccountInfo = Context.AccountInfo.FirstOrDefault();

//            record.ParentContract = Context.Contracts.Find(rec.DataSubject.ParentContractID);

            Context.Requests.Add(record);

            await Context.SaveChangesAsync();

            return Transformers.Transform(record, new RequestDTO());
        }

        public async Task<RequestDTO> Put(SaveMessage<RequestDTO> rec)
        {
            var ctr = await Context.Requests.Where(c => c.ID == rec.ID)
                .Include( p => p.Teammembers)
                .FirstOrDefaultAsync();

            if (ctr == null)
            {
                return null;
            }

            ctr = Transformers.Transform(rec.DataSubject, ctr);

            await Context.SaveChangesAsync();

            return Transformers.Transform(ctr, new RequestDTO());
        }

        public async Task<bool> Delete(SaveMessage<RequestDTO> rec)
        {
            var ctr = Context.Requests.FirstOrDefault(c => c.ID == rec.ID);

            if (ctr == null)
            {
                return false;
            }

            Context.Requests.Remove(ctr);

            await Context.SaveChangesAsync();

            return true;
        }

        public async Task<RequestDTO> Get(int id)
        {
            var record = await Context.Requests.Where(c => c.ID == id)
                .Include( p => p.Teammembers)
                .FirstOrDefaultAsync();

            var ctr = Transformers.Transform(record, new RequestDTO() { Modifier = "Unchanged" });

            return ctr;
        }

    }
}
