/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 04/Jan/2021 21:46:21
** YOU CAN MODIFY IT, as it will not be regenerated.
** If you want to regenrate this file simply delete it.
*/
using System;
using System.Collections.Generic;
using upromiscontractapi.Models;

namespace upromiscontractapi.Business
{
    partial class AccountInfoBusinessRules : IAccountInfoBusinessRules
    {
        partial void OnApplyBusinessRules(AccountInfo Record, AccountInfoDTO DTORecord, IRepository<AccountInfo> Repository)
        {

        }
    }
}
