// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uPromis.Microservice.AttachmentAPI;

namespace uPromis.Microservice.AttachmentAPI.Migrations
{
    [DbContext(typeof(AttachmentContext))]
    [Migration("20200515184524_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("uPromis.Microservice.AttachmentAPI.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(40);

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasColumnName("blobcontainer")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnName("blobname")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnName("filename")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<Guid>("ParentItem")
                        .HasColumnName("parentitem")
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(40);

                    b.Property<long>("Size")
                        .HasColumnName("size")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnName("uploadedby")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256)
                        .IsUnicode(false);

                    b.Property<DateTimeOffset>("UploadedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("uploadedon")
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("files");
                });
#pragma warning restore 612, 618
        }
    }
}
